Write-Warning 'This command has been deprecated in favor of the PowerShell Gallery'
Write-Warning '  To Install: Use "Install-Module -Name Rubrik -Scope CurrentUser"'
Write-Warning '  To Upgrade: Use "Update-Module -Name Rubrik"'
Write-Warning 'See the online documentation for more details'
Write-Warning '  http://powershell-module.readthedocs.io/en/latest/installation.html'