name: Enhancement Request
description: Suggest an enhancement to the Rubrik SDK for PowerShell.
labels: ["kind-enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please only use this template for submitting enhancement requests.  
        Any enhancement requests submitted will be visible publicly, do not include confidential information in this enhancement request.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
