  query MyVMs ($filter: [Filter!]) {
    data: vSphereVmNewConnection(filter: $filter) {
      objects: nodes {
        id
        name
        isRelic
        slaAssignment
        effectiveSlaDomain {
          id
          name
        }
        configuredSlaDomain {
          id
          name
        }
        cluster {
          id
          name
        }
        objectType
        guestOsName
        guestOsType
        agentStatus {
          agentStatus
        }
        powerStatus
        
      }
    }
  }